### PR TITLE
Unity Project Files

### PR DESCRIPTION
**Pull request by kevinthedang**
## Changes
* The `.gitignore` scope covers the whole repository so this can cover multiple Unity Project files if needed (but not recommended)
* The initial project files were created using Unity version 2022.3.34fl with **OpenJDK**, the **Android SDK & NDK Tools**, and the **Documentation** modules.
* Changes the logo to reflect what the project is supposed to be. It would be nice to change this to be "AsteroidsVR" graphically, maybe in its own style or similar to the original.
* Added the URP docs that reflect the projects intended target version.

### CODE REVIEW

**Comment by kevinthedang** [comment]
Will reference #1 here

**Review by JT2M0L3Y — APPROVED** [review]
VR Asteroids it is then.

**Review by JT2M0L3Y — APPROVED** [review]

**Review by JT2M0L3Y — APPROVED** [review]
This has been reviewed and is in keeping with the plans for what type of VR game should be developed.

**Comment by kevinthedang** [comment]
Fixed issue with Approvals not going through

**Pull request merged**
